import type { Root as MdastRoot } from "mdast";
import type { Root as HastRoot } from "hast";
import type { TocNode, CaptionEntry, FormatPreset } from "./format";

/**
 * A single section parsed into AST.
 * See Design/Modules/Other/CanonicalTypes.md §7.
 */
export type ParsedSection = {
  sectionId: string;
  markdown: string;
  ast: MdastRoot;         // mdast Root from remark-parse
  updatedAt: string;      // ISO 8601
};

/**
 * Output of the orchestrator after merging and parsing all sections.
 * See Design/Modules/Other/CanonicalTypes.md §7.
 */
export type PipelineResult = {
  projectId: string;
  sections: ParsedSection[];
  combinedMdast: MdastRoot;
  updatedAt: string;      // ISO 8601
};

/**
 * The fully formatted and numbered report.
 * Generated by Format, consumed by Check and Export.
 */
export type FormattedReport = {
  projectId: string;
  toc: TocNode[];
  figures: CaptionEntry[];
  tables: CaptionEntry[];
  preset: FormatPreset;
  hast: HastRoot;         // for HTML/PDF rendering (Module 4)
  mdast: MdastRoot;       // formatted nodes for DOCX rendering (Module 4)
};

