export { generateSlideOutline } from "./generate-outline";
export { buildTimeline } from "./timeline";
export { buildSpeakers, assignSlides } from "./speakers";
export { generateSpeakerScript } from "./generate-script";
export { generateDefenseQA } from "./generate-qa";
export { buildWeakSectionHints } from "./weak-sections";
export { ScriptView } from "./ScriptView";
export { DefenseQAView } from "./DefenseQAView";
export { PresentPanel } from "./PresentPanel";
export { MockDefenseView } from "./MockDefenseView";
export { generateMockDefenseQuestions, parseDefenseQuestions } from "./mock-defense/generate-questions";
export { evaluateMockDefenseAnswer, parseAnswerVerdict } from "./mock-defense/evaluate-answer";
export { createMockDefenseSession, answerCurrentTurn, finishMockDefenseSession } from "./mock-defense/session";
export { buildReadinessScorecard } from "./mock-defense/scorecard";
export { MOCK_DEFENSE_PERSONAS } from "./mock-defense/personas";
export { assistOutline } from "./ai/assist-outline";
export { AiOutlineButton } from "./ai/AiOutlineButton";
export { buildPptx } from "./export-pptx";
